package model;

java.util.Date;

public class Report {
    private int number;//autogenerated
    private double xCoordinate;
    private double yCoordinate;
    private Date submitted;//autogenerated (stored as Date, accessed as String)
    private User reporter;//autogenerated
    private User verifier;
    private String type;//need on creation
    private String condition;

    public Report(double x, double y, String type, String condition, String Type, String Condition) {
        //TODO: autogenerate number
        xCoordinate = x;
        yCoordinate = y;
        submitted = new Date();
        reporter = "";//TODO: autogenerate
        verifier = "";//TODO: autogenerate afterwards?
        type = Type;
        condition = Condition;
    }

    public void getNumber() {
        return number;
    }

    public void setX(double x) {
        this.xCoordinate = x;
    }

    public double getX() {
        return xCoordinate;
    }

    public void setY(double y) {
        this.yCoordinate = y;
    }

    public double getY() {
        return yCoordinate;
    }

    public String getDate() {
        return new SimpleDateFormat("yyyy.MM.dd.HH.mm").format(submitted);
    }

    public User getReporter() {
        return reporter;
    }

    public void setVerifier(User verifier) {
        this.verifier = verifier;
    }

    public User getVerifier() {
        return verifier;
    }

    public String getType() {
        return type;
    }

    public void setCondition(String Condition) {
        this.condition = Condition;
    }

    public String getCondition() {
        return condition;
    }
}